export const empleados = [
{
    num_empleado: 1,
    nombres: 'Juan',
    apellidos: 'Pérez',
    identidad: '123456789',
    correo: 'fgarcia0300@gmail.com',
    password: 'password1',
    foto: 'https://example.com/foto1.jpg',
    centro: 'Centro Educativo A',
    cargo: 'Docente',
    departamento: 'Ingenieria en Sistemas',
  },
  {
    num_empleado: 2,
    nombres: 'María',
    apellidos: 'González',
    identidad: '987654321',
    correo: 'maria.gonzalez@example.com',
    password: 'password2',
    foto: 'https://example.com/foto2.jpg',
    centro: 'Centro Educativo B',
    cargo: 'Docente',
    departamento: 'Ingenieria en Sistemas',
  },
  {
    num_empleado: 3,
    nombres: 'Carlos',
    apellidos: 'López',
    identidad: '456789123',
    correo: 'carlos.lopez@example.com',
    password: 'password3',
    foto: 'https://example.com/foto3.jpg',
    centro: 'Centro Educativo C',
    cargo: 'Docente',
    departamento: 'Ingenieria en Sistemas',
  },
];